name = "SimLynx"
uuid = "4afcfb46-fe9b-4036-bc19-7ccfa92ea78e"
authors = ["Trystan Kaes <trystanblkaes@gmail.com>", "Anthony Dupont <>\"anthony.dupont@ucdenver.edu>", "Doug Williams <milton.williams@ucdenver.edu>"]
version = "0.3.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Documenter = "0.25"
Plots = "1.9"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
